param (
    [ScriptBlock]$ContentBlock
)

New-HTML -Online -Minify -TitleText 'My Dashboard' {
    # Clean Header Section with built-in styling
    New-HTMLSection `
        -HeaderText '☰ Menu' `
        -HeaderTextAlignment 'center' `
        -HeaderBackGroundColor '#085fd1' `
        -BackgroundColor '#085fd1' `
        -Direction 'column' `
        -CanCollapse {

            New-HTMLTag -Tag 'h2' -Attributes @{ style = 'color:white; text-align:left; margin:0;' } -Content { '☁️ Cloud Reports' }

            New-HTMLTag -Tag 'div' -Attributes @{ style = 'text-align:left; padding-top:10px;' } -Content {
                New-HTMLTag -Tag 'a' -Attributes @{ href = '/' ; style = 'margin-right:15px; color:white; text-decoration:none; font-weight:bold;' } -Content { '🏠 Home' }
                New-HTMLTag -Tag 'a' -Attributes @{ href = '/report1'; style = 'margin-right:15px; color:white; text-decoration:none; font-weight:bold;' } -Content { '📋 Report 1' }
                New-HTMLTag -Tag 'a' -Attributes @{ href = '/report2'; style = 'margin-right:15px; color:white; text-decoration:none; font-weight:bold;' } -Content { '📊 Report 2' }
                New-HTMLTag -Tag 'a' -Attributes @{ href = '/report3'; style = 'margin-right:15px; color:white; text-decoration:none; font-weight:bold;' } -Content { '📈 Report 3' }
            }
    }

    # Main content block
    & $ContentBlock

    # Footer
    
    New-HTMLSection `
        -HeaderText 'Footer' `
        -HeaderTextAlignment 'center' `
        -HeaderBackGroundColor '#085fd1' `
        -BackgroundColor '#085fd1' `
        -Direction 'column' `
        -Collapsed `
        -CanCollapse {
            New-HTMLTag -Tag 'div' -Attributes @{ style = 'color:white; padding:10px; font-size:smaller;' } -Content {
                New-HTMLText -Text "© $(Get-Date -Format yyyy) Cenovus CloudOps"
                New-HTMLText -Text "Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
                New-HTMLText -Text "Version: 1.0.0"
                New-HTMLText -Text "Generated by: Cenovus CloudOps Team"
            }        
    }
}