param (
    [ScriptBlock]$ContentBlock,
    [string]$CurrentPage
)

$Pages = @(
    @{ Name = 'Home'; Path = '/'; Icon = '🏠' },
    @{ Name = 'Report1'; Path = '/report1'; Icon = '📋' },
    @{ Name = 'Report2'; Path = '/report2'; Icon = '📊' },
    @{ Name = 'Report3'; Path = '/report3'; Icon = '📈' }
)

New-HTML -Online -Minify -TitleText 'My Dashboard' {

    # Inject working global CSS
    New-HTMLTag -Tag 'style' -Attributes @{ type = 'text/css' } -Content {
@"
a.nav-link,
a.nav-link:visited {
    color: white !important;
    font-weight: bold;
    text-decoration: none;
    transition: all 0.2s ease-in-out;
}

a.nav-link:hover {
    color:rgb(230, 90, 20) !important;
    text-decoration: underline;
}

a.nav-link.active {
    color: cyan !important;
}
"@
    }

    # Header / Navigation
    New-HTMLSection `
        -HeaderText '☰ Menu' `
        -HeaderTextAlignment 'center' `
        -HeaderBackGroundColor '#085fd1' `
        -BackgroundColor '#085fd1' `
        -Direction 'column' `
        -CanCollapse {

        New-HTMLTag -Tag 'h2' -Attributes @{ style = 'color:white; text-align:left; margin:0;' } -Content { '☁️ Cloud Reports' }

        New-HTMLTag -Tag 'div' -Attributes @{ style = 'text-align:left; padding-top:10px;' } -Content {
            foreach ($page in $Pages) {
                $isActive = $page.Name -eq $CurrentPage
                $className = if ($isActive) { 'nav-link active' } else { 'nav-link' }

                New-HTMLTag -Tag 'a' -Attributes @{
                    href  = $page.Path
                    class = $className
                    style = 'margin-right:15px;'
                } -Content { "$($page.Icon) $($page.Name)" }
            }
        }
    }

    # Main content block
    & $ContentBlock

    # Footer
    New-HTMLSection `
        -HeaderText 'Footer' `
        -HeaderTextAlignment 'center' `
        -HeaderBackGroundColor '#085fd1' `
        -BackgroundColor '#085fd1' `
        -Direction 'column' `
        -Collapsed `
        -CanCollapse {
            New-HTMLTag -Tag 'div' -Attributes @{ style = 'color:white; padding:10px; font-size:smaller;' } -Content {
                New-HTMLText -Text "© $(Get-Date -Format yyyy) Cenovus CloudOps"
                New-HTMLText -Text "Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
                New-HTMLText -Text "Version: 1.0.0"
                New-HTMLText -Text "Generated by: Cenovus CloudOps Team"
            }
        }

} # end New-HTML
