param (
    [ScriptBlock]$ContentBlock,
    [string]$CurrentPage
)

$Pages = @(
    @{ Name = 'Home'; Path = '/'; Icon = '🏠' },
    @{ Name = 'Report1'; Path = '/report1'; Icon = '📋' },
    @{ Name = 'Report2'; Path = '/report2'; Icon = '📊' },
    @{ Name = 'Report3'; Path = '/report3'; Icon = '📈' }
)

New-HTML -Online -Minify -TitleText 'My Dashboard' {

    <# Inject working global CSS
        Serving up web pages via Pode is simple, you can either write your pages in HTML, Pode, another template engine; 
        then place those files within the /views directory. 
        You can also use CSS, JavaScript, Images, etc. and place those files within the /public directory.
        
        If your web page references any CSS, JavaScript, etc. files, then Pode will automatically find them within the /public directory - or 
        any relative static routes you may have defined. 
        For example, if you reference <link rel="stylesheet" type="text/css" href="/styles/simple.css"> in your HTML file, then Pode will look for /public/styles/simple.css.
    #>
    New-HTMLTag -Tag 'link' -Attributes @{
        rel  = 'stylesheet'
        type = 'text/css'
        href = '/css/styles.css'  # Path matches Pode static route
    }

    # Header / Navigation
    New-HTMLSection `
        -HeaderText '☰ Menu' `
        -HeaderTextAlignment 'center' `
        -HeaderBackGroundColor '#085fd1' `
        -BackgroundColor '#085fd1' `
        -Direction 'column' `
        -CanCollapse {

        New-HTMLTag -Tag 'h2' -Attributes @{ style = 'color:white; text-align:left; margin:0;' } -Content { '☁️ Cloud Reports' }

        New-HTMLTag -Tag 'div' -Attributes @{ style = 'text-align:left; padding-top:10px;' } -Content {
            foreach ($page in $Pages) {
                $isActive = $page.Name -eq $CurrentPage
                $className = if ($isActive) { 'nav-link active' } else { 'nav-link' }

                New-HTMLTag -Tag 'a' -Attributes @{
                    href  = $page.Path
                    class = $className
                    style = 'margin-right:15px;'
                } -Content { "$($page.Icon) $($page.Name)" }
            }
        }
    }

    # Main content block
    & $ContentBlock

    # Footer
    New-HTMLSection `
        -HeaderText 'Footer' `
        -HeaderTextAlignment 'center' `
        -HeaderBackGroundColor '#085fd1' `
        -BackgroundColor '#085fd1' `
        -Direction 'column' `
        -Collapsed `
        -CanCollapse {
            New-HTMLTag -Tag 'div' -Attributes @{ style = 'color:white; padding:10px; font-size:smaller;' } -Content {
                New-HTMLText -Text "© $(Get-Date -Format yyyy) Cenovus CloudOps"
                New-HTMLText -Text "Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
                New-HTMLText -Text "Version: 1.0.0"
                New-HTMLText -Text "Generated by: Cenovus CloudOps Team"
            }
        }

} # end New-HTML